### PR TITLE
Fix busted dates that should be negative

### PR DESCRIPTION
**Pull request by mjgiarlo**
Needs review by @jacobthill

### CODE REVIEW

**Comment by ndushay** [comment]
note that some, but not all, of these could fall back to `date_made` column.

That is, if invalid range from `date_made_early` and `date_made_late` column values, try to parse `date_made` value for valid date range.

Of course, it would be better if the data was ... clean.

**Comment by anarchivist** [comment]
We should avoid making changes in the harvested data if at all possible.

**Comment by mjgiarlo** [comment]
Yeah, I don't particularly care *how* the data is changed, but I thought this was an easy way to reflect what's currently busted. Defer totally to @jacobthill. Until these data changes flow into dlme-metadata, our integration specs for dlme-transform will break.

**Comment by mjgiarlo** [comment]
Not going to move forward with this. Instead we will add a flag to allow years to come back out of order, and will simply map them to nil instead of raising.

**Pull request closed without merging**
